const products = [
  {
    _id: "1",
    name: "a",
    image: "/images/1.jpg",
    description: "asd asdasd asd asd",
    brand: "Apple",
    category: "Electronics",
    price: "89.99",
    countIStock: "1",
    rating: "3.5",
    numReviews: "10",
  },
  {
    _id: "2",
    name: "a",
    image: "/images/1.jpg",
    description: "asd asdasd asd asd",
    brand: "Apple",
    category: "Electronics",
    price: "89.99",
    countIStock: "10",
    rating: "4.5",
    numReviews: "12",
  },
  {
    _id: "3",
    name: "a",
    image: "/images/1.jpg",
    description: "asd asdasd asd asd",
    brand: "Apple",
    category: "Electronics",
    price: "89.99",
    countIStock: "10",
    rating: "3.2",
    numReviews: "12",
  },
  {
    _id: "4",
    name: "a",
    image: "/images/1.jpg",
    description: "asd asdasd asd asd",
    brand: "Apple",
    category: "Electronics",
    price: "89.99",
    countIStock: "10",
    rating: "2.5",
    numReviews: "12",
  },
  {
    _id: "5",
    name: "a",
    image: "/images/1.jpg",
    description: "asd asdasd asd asd",
    brand: "Apple",
    category: "Electronics",
    price: "89.99",
    countIStock: "10",
    rating: "5",
    numReviews: "12",
  },
  {
    _id: "6",
    name: "a",
    image: "/images/1.jpg",
    description: "asd asdasd asd asd",
    brand: "Apple",
    category: "Electronics",
    price: "89.99",
    countIStock: "10",
    rating: "4.5",
    numReviews: "12",
  },
];

export default products;
